eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
  instance:
    prefer-ip-address: true
#    ipAddress: 127.0.0.1
#    instanceId: localhost:${spring.application.name}:${server.port}
#    appname: ${spring.application.name}    
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder    
